spring:
  main:
    allow-circular-references: true

# Upload interface
com.yidan.tus:
  upload-URI: /api/upload/
  # tus chunk file storage location
  tus-upload-directory: ${tus.filePath}/
  # The location where the file was finally uploaded
  app-upload-directory: ${cms.filePath}/web/upload
  # Whether to open the lock file of regularly cleaning tus, the default is false
  enable-clean: true
  # Timing period
  expire-time: 1MINUTES
