version: '3'
services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ${HOME_DIR}/data/:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
